services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        env_file: .env
    mysql:
        image: mysql:9.1.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: newsper
            MYSQL_USER: newsper
            MYSQL_PASSWORD: newsper
    redis:
        image: redis:7.4.1